import { randomUUID } from "node:crypto";
import { load } from "cheerio";
import type { Pool } from "pg";
import { ReviewedHttpDiscoveryConnector, type SourceParser } from "../connectors/discovery_http.js";
import type { DiscoverySourceKind } from "../discovery.js";
import type { ImmutableEvidenceStore } from "./object_store.js";
import { inTransaction } from "./database.js";
import type { SensitiveDataCipher } from "./sensitive_data.js";

type JsonParserConfig={type:"JSON_ARRAY";arrayPath:string;nameField:string;websiteField?:string;registrationField?:string};
type HtmlParserConfig={type:"HTML_TABLE";rowSelector:string;nameSelector:string;websiteSelector?:string;registrationSelector?:string;linkSelector?:string};
type ParserConfig=JsonParserConfig|HtmlParserConfig;
function at(value:unknown,path:string):unknown{return path?path.split(".").reduce<unknown>((current,key)=>current&&typeof current==="object"?(current as Record<string,unknown>)[key]:undefined,value):value}
function safeText(value:unknown):string|undefined{return typeof value==="string"&&value.trim()?value.trim():undefined}
function parser(config:ParserConfig):SourceParser{return{async parse(input){if(config.type==="JSON_ARRAY"){const rows=at(JSON.parse(new TextDecoder("utf-8",{fatal:true}).decode(input.body)),config.arrayPath);if(!Array.isArray(rows))throw new Error("discovery JSON array missing");return{links:[],candidates:rows.flatMap((row,index)=>{const name=safeText(at(row,config.nameField));if(!name)return[];const registration=config.registrationField?safeText(at(row,config.registrationField)):undefined;return[{candidateId:`${input.receipt.sha256.slice(0,20)}-${index}`,legalName:name,website:config.websiteField?safeText(at(row,config.websiteField))??null:null,registrationIdentifier:registration??null,registrationState:registration?"SOURCE_STATED" as const:"UNVERIFIED" as const,discoveredAt:input.retrievedAt}]})}}const $=load(new TextDecoder("utf-8",{fatal:true}).decode(input.body)),links:string[]=[],candidates:Awaited<ReturnType<SourceParser["parse"]>>["candidates"][number][]=[];$(config.rowSelector).each((index,element)=>{const name=$(element).find(config.nameSelector).first().text().trim();if(!name)return;const website=config.websiteSelector?$(element).find(config.websiteSelector).first().attr("href")?.trim():undefined,registration=config.registrationSelector?$(element).find(config.registrationSelector).first().text().trim():undefined;candidates.push({candidateId:`${input.receipt.sha256.slice(0,20)}-${index}`,legalName:name,website:website??null,registrationIdentifier:registration||null,registrationState:registration?"SOURCE_STATED":"UNVERIFIED",discoveredAt:input.retrievedAt})});if(config.linkSelector)$(config.linkSelector).each((_index,element)=>{const href=$(element).attr("href");if(href)links.push(href)});return{links,candidates}}}}

export class ProductionDiscoveryService{
 constructor(readonly pool:Pool,readonly store:ImmutableEvidenceStore,readonly cipher:SensitiveDataCipher){}
 async run(sourceId:string,expectedRole:"SUPPLIER"|"BUYER"):Promise<{receiptIds:readonly string[];candidateCount:number;stoppedReason:string}>{
  const source=(await this.pool.query("select s.* from discovery_source_configs s join authority_receipts a on a.receipt_id=s.source_policy_receipt_id where s.id=$1 and s.role=$2 and s.state='APPROVED' and s.valid_from<=now() and s.valid_until>now() and a.effective_at<=now() and a.expires_at>now()",[sourceId,expectedRole])).rows[0];if(!source)throw new Error("reviewed discovery source unavailable");const hosts=source.allowed_hosts;if(!Array.isArray(hosts)||hosts.some(value=>typeof value!=="string"))throw new Error("discovery hosts invalid");
  const connector=new ReviewedHttpDiscoveryConnector(source.source_kind as DiscoverySourceKind,{sourceAllowed:true,robotsAllowed:true,termsReviewed:true,maxPages:source.maximum_pages,allowedHosts:hosts},this.store,parser(source.parser_config as ParserConfig)),result=await connector.harvest(source.seed_url),receiptIds:string[]=[];
  await inTransaction(this.pool,async client=>{for(const page of result.pages){let receipt=(await client.query("select id from discovery_receipts where canonical_url=$1 and body_sha256=$2",[page.canonicalUrl,page.bodySha256])).rows[0];if(!receipt)receipt=(await client.query("insert into discovery_receipts(id,source_kind,canonical_url,retrieved_at,body_sha256,body_object_key,policy_version) values($1,$2,$3,$4,$5,$6,$7) returning id",[randomUUID(),source.source_kind,page.canonicalUrl,page.retrievedAt,page.bodySha256,page.bodyObjectKey,`source:${source.id}`])).rows[0];receiptIds.push(String(receipt.id));for(const candidate of result.candidates.filter(value=>value.sourcePageUrl===page.canonicalUrl)){let stored=(await client.query("select id from organization_candidates where discovery_receipt_id=$1 and legal_name=$2 and coalesce(registration_identifier,'')=coalesce($3,'')",[receipt.id,candidate.legalName,candidate.registrationIdentifier])).rows[0];if(!stored)stored=(await client.query("insert into organization_candidates(id,discovery_receipt_id,legal_name,website,registration_identifier,registration_state,discovered_at) values($1,$2,$3,$4,$5,$6,$7) returning id",[randomUUID(),receipt.id,candidate.legalName,candidate.website,candidate.registrationIdentifier,candidate.registrationState,candidate.discoveredAt])).rows[0];const domain=candidate.website?new URL(candidate.website).hostname.toLowerCase():null,identity=this.cipher.lookup(candidate.registrationIdentifier?`registration:${candidate.registrationIdentifier}`:domain?`domain:${domain}`:`name:${candidate.legalName}`),known=(await client.query("select organization_id from organization_identity_keys where identity_hash=$1",[identity])).rows[0];let organizationId=known?.organization_id;if(!organizationId){organizationId=randomUUID();await client.query("insert into organizations(id,organization_type,legal_name_ciphertext) values($1,$2,$3)",[organizationId,expectedRole,this.cipher.encrypt(candidate.legalName)]);await client.query("insert into organization_identity_keys(identity_hash,organization_id,candidate_id) values($1,$2,$3)",[identity,organizationId,stored.id])}await client.query("insert into candidate_organizations(candidate_id,organization_id,role) values($1,$2,$3) on conflict(candidate_id) do nothing",[stored.id,organizationId,expectedRole]);if(domain)await client.query("insert into enrichment_jobs(id,candidate_id,organization_id,domain,state) values($1,$2,$3,$4,'PENDING') on conflict(candidate_id) do nothing",[randomUUID(),stored.id,organizationId,domain])}}});
  await this.pool.query("insert into kyb_jobs(id,organization_id,candidate_id,country_code,state) select gen_random_uuid(),co.organization_id,co.candidate_id,'IN','PENDING' from candidate_organizations co where co.role=$1 and not exists(select 1 from kyb_jobs k where k.organization_id=co.organization_id)",[expectedRole]);
  return{receiptIds:Object.freeze(receiptIds),candidateCount:result.candidates.length,stoppedReason:result.stoppedReason};
 }
}
