import {createHash} from "node:crypto";
import {GetObjectCommand,GetObjectLockConfigurationCommand,HeadObjectCommand,PutObjectCommand,S3Client} from "@aws-sdk/client-s3";

export interface EvidenceReceipt {readonly objectKey:string;readonly sha256:string;readonly bytes:number;readonly contentType:string;readonly storedAt:string;readonly source:string;}
export interface EvidenceStoreConfig {readonly endpoint:string;readonly region:string;readonly bucket:string;readonly accessKeyId:string;readonly secretAccessKey:string;readonly forcePathStyle:boolean;readonly requireObjectLock?:boolean;}
export class ImmutableEvidenceStore{
 readonly client:S3Client;constructor(readonly config:EvidenceStoreConfig){if(!config.bucket||!config.endpoint.startsWith("http"))throw new Error("object store configuration invalid");this.client=new S3Client({endpoint:config.endpoint,region:config.region,forcePathStyle:config.forcePathStyle,credentials:{accessKeyId:config.accessKeyId,secretAccessKey:config.secretAccessKey}})}
 async preserve(prefix:string,body:Uint8Array,contentType:string,source:string,storedAt=new Date().toISOString()):Promise<EvidenceReceipt>{const digest=createHash("sha256").update(body).digest("hex"),key=`${prefix}/${digest}`;try{const head=await this.client.send(new HeadObjectCommand({Bucket:this.config.bucket,Key:key}));if(Number(head.ContentLength)!==body.byteLength||head.Metadata?.["sha256"]!==digest)throw new Error("immutable evidence collision")}catch(error){if((error as {name?:string}).name!=="NotFound"&&((error as {$metadata?:{httpStatusCode?:number}}).$metadata?.httpStatusCode!==404))throw error;await this.client.send(new PutObjectCommand({Bucket:this.config.bucket,Key:key,Body:body,ContentType:contentType,Metadata:{sha256:digest,source},IfNoneMatch:"*",ServerSideEncryption:"AES256"}))}return Object.freeze({objectKey:key,sha256:digest,bytes:body.byteLength,contentType,storedAt,source});}
 async read(receipt:EvidenceReceipt):Promise<Uint8Array>{const response=await this.client.send(new GetObjectCommand({Bucket:this.config.bucket,Key:receipt.objectKey})),bytes=await response.Body?.transformToByteArray();if(!bytes||createHash("sha256").update(bytes).digest("hex")!==receipt.sha256)throw new Error("evidence digest mismatch");return bytes;}
 async readVerified(objectKey:string,sha256:string):Promise<Uint8Array>{if(!objectKey.trim()||!/^[0-9a-f]{64}$/.test(sha256))throw new Error("evidence reference invalid");return this.read({objectKey,sha256,bytes:0,contentType:"application/octet-stream",storedAt:"",source:""})}
 async assertRetentionPolicy():Promise<void>{if(!this.config.requireObjectLock)return;const state=await this.client.send(new GetObjectLockConfigurationCommand({Bucket:this.config.bucket}));if(state.ObjectLockConfiguration?.ObjectLockEnabled!=="Enabled"||state.ObjectLockConfiguration.Rule?.DefaultRetention?.Mode!=="COMPLIANCE")throw new Error("evidence bucket requires COMPLIANCE Object Lock default retention")}
}
