begin;
alter table matches drop column if exists expected_days_to_cash;
alter table matches drop column if exists priority_source_digest;
alter table matches drop column if exists priority_state;
alter table settlement_instructions drop column if exists waterfall_digest;
alter table settlement_instructions drop column if exists provider_deductions;
alter table settlement_instructions drop column if exists buyer_direct_costs;
alter table settlement_instructions drop column if exists buyer_all_in_amount;
alter table settlement_instructions drop column if exists final_economics_snapshot_id;
drop trigger if exists final_economics_waterfall_validate on final_economics_snapshots;
drop function if exists validate_final_economics_waterfall();
alter table final_economics_snapshots drop constraint if exists final_economics_buyer_all_in_check;
alter table final_economics_snapshots drop column if exists waterfall_digest;
alter table final_economics_snapshots drop column if exists buyer_direct_costs;
alter table final_economics_snapshots drop column if exists reserve_allocations;
alter table final_economics_snapshots drop column if exists provider_deductions;
alter table final_economics_snapshots drop column if exists third_party_allocations;
alter table final_economics_snapshots drop column if exists buyer_direct_per_kg;
alter table final_economics_snapshots drop column if exists settlement_gross_per_kg;
alter table final_economics_snapshots drop column if exists settlement_supplier_per_kg;
alter table cost_components drop column if exists beneficiary_id;
alter table cost_components drop column if exists beneficiary_role;
alter table cost_components drop column if exists settlement_treatment;
alter table cost_components drop column if exists payer_role;
delete from schema_migrations where version='0054_explicit_waterfall_and_opportunity_set';
commit;
