begin;
drop table if exists settlement_allocation_links;
drop table if exists counterparty_dispute_requests;
drop table if exists identity_provisioning_jobs;
drop table if exists counterparty_principals;
drop table if exists counterparty_action_notifications;
drop table if exists counterparty_actions;
drop table if exists supplier_payout_controls;
drop table if exists protected_transaction_terms;
alter table standing_renewal_reservations drop column if exists final_economics_snapshot_id;
alter table standing_renewal_reservations drop column if exists trade_id;
alter table standing_renewal_reservations drop column if exists committed_at;
alter table standing_renewal_reservations drop constraint standing_renewal_reservations_state_check;
alter table standing_renewal_reservations add constraint standing_renewal_reservations_state_check check(state in('RESERVED','CONSUMED','RELEASED'));
drop index if exists standing_renewal_reservations_live_cycle;
create unique index standing_renewal_reservations_live_cycle on standing_renewal_reservations(demand_id,demand_version,cycle_number) where state in('RESERVED','CONSUMED');
drop index if exists external_event_inbox_redrive;
alter table external_event_inbox drop column if exists redrive_count;
alter table external_event_inbox drop column if exists failure_class;
alter table external_event_inbox drop column if exists next_retry_at;
alter table external_event_inbox drop constraint external_event_inbox_processing_state_check;
alter table external_event_inbox add constraint external_event_inbox_processing_state_check check(processing_state in('PENDING','PROCESSING','PROCESSED','REJECTED'));
delete from schema_migrations where version='0059_launch_hardening';
commit;
