import{createHmac,timingSafeEqual}from"node:crypto";import type{ProviderCapabilitySnapshot,SettlementAdapter,SettlementCapability,SettlementEnvironment,SettlementInstructionDraft}from"../settlement.js";import{assertAdapterAvailable,assertSettlementInstruction,evaluateProviderCapability,requiredSettlementCapabilities,type ProviderApproval,type ProviderCredentials}from"../settlement.js";import type{ReceiptWriter}from"./discovery_http.js";
export interface ProviderHttpConfig{readonly provider:string;readonly baseUrl:string;readonly createPath:string;readonly authorizationHeader:string;readonly additionalHeaders:Readonly<Record<string,string>>;readonly webhookSecret:string;readonly webhookSignatureHeader?:string;readonly webhookEventIdPath?:string;readonly webhookEventTypePath?:string;readonly webhookProviderReferencePath?:string;readonly webhookOccurredAtPath?:string;readonly webhookAmountPath?:string;readonly webhookCurrencyPath?:string;readonly webhookBankReferencePath?:string;readonly webhookEventTypeMap?:Readonly<Record<string,"FUNDED"|"DISBURSEMENT_REPORTED"|"FAILED"|"REVERSED"|"DISPUTE_OPENED">>;readonly responseReferenceField:string;readonly responseAcknowledgedField:string;}
export type SettlementRequestBuilder=(draft:SettlementInstructionDraft)=>Readonly<Record<string,unknown>>;
export class ProductionSettlementHttpAdapter implements SettlementAdapter{
 readonly environment:SettlementEnvironment="PRODUCTION";constructor(readonly provider:string,readonly approval:ProviderApproval,readonly credentials:ProviderCredentials,readonly config:ProviderHttpConfig,readonly buildRequest:SettlementRequestBuilder,readonly store:ReceiptWriter,readonly fetcher:typeof fetch=fetch){if(provider!==approval.provider||provider!==credentials.provider||provider!==config.provider)throw new Error("settlement provider configuration mismatch")}
 capability(required:readonly SettlementCapability[],now:string):ProviderCapabilitySnapshot{return evaluateProviderCapability(this.approval,this.credentials,required,now)}
 async createInstruction(draft:SettlementInstructionDraft,now:string):Promise<Readonly<{state:"CREATED";providerReference:string;acknowledged:boolean}>>{const snapshot=this.capability(requiredSettlementCapabilities(this.provider),now);assertAdapterAvailable(snapshot);assertSettlementInstruction(draft,this.approval,now);if(draft.environment!=="PRODUCTION")throw new Error("production adapter requires production draft");const url=new URL(this.config.createPath,this.config.baseUrl),payload=JSON.stringify(this.buildRequest(draft)),requestReceipt=await this.store.preserve(`settlement/${this.provider}/request`,new TextEncoder().encode(payload),"application/json",url.toString(),now),response=await this.fetcher(url,{method:"POST",headers:{authorization:this.config.authorizationHeader,"content-type":"application/json","idempotency-key":draft.idempotencyKey,...this.config.additionalHeaders},body:payload,signal:AbortSignal.timeout(30_000)}),bytes=new Uint8Array(await response.arrayBuffer()),responseReceipt=await this.store.preserve(`settlement/${this.provider}/response`,bytes,response.headers.get("content-type")??"application/json",url.toString(),now);if(!response.ok)throw new Error(`${this.provider} HTTP ${response.status}; request=${requestReceipt.objectKey}; response=${responseReceipt.objectKey}`);const decoded=JSON.parse(new TextDecoder().decode(bytes))as Record<string,unknown>,reference=field(decoded,this.config.responseReferenceField),acknowledged=field(decoded,this.config.responseAcknowledgedField);if(typeof reference!=="string"||!reference.trim()||acknowledged!==true)throw new Error(`${this.provider} acknowledgement incomplete; response=${responseReceipt.objectKey}`);return Object.freeze({state:"CREATED",providerReference:reference,acknowledged:true})}
 verifyWebhook(rawBody:Uint8Array,signatureHex:string):void{if(!this.config.webhookSecret||!/^[0-9a-f]+$/i.test(signatureHex))throw new Error("settlement webhook signature malformed");const expected=createHmac("sha256",this.config.webhookSecret).update(rawBody).digest(),supplied=Buffer.from(signatureHex,"hex");if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))throw new Error("settlement webhook signature invalid")}
}
function field(value:Record<string,unknown>,path:string):unknown{return path.split(".").reduce<unknown>((current,key)=>current&&typeof current==="object"?(current as Record<string,unknown>)[key]:undefined,value)}
export const escrowComRequest:SettlementRequestBuilder=draft=>({currency:draft.currency,description:`SableStone protected polymer trade ${draft.tradeId}`,parties:[{role:"buyer",customer:draft.buyerId},{role:"seller",customer:draft.supplierId},{role:"broker",customer:draft.sablestoneBeneficiaryId}],items:[{type:"general_merchandise",title:draft.commodityFamily,quantity:1,inspection_period:259200,fees:[{payer_customer:draft.buyerId,type:"broker_fee",amount:draft.sablestoneEntitlement}],schedule:[{amount:draft.supplierEntitlement,beneficiary_customer:draft.supplierId}]}],metadata:{instruction_id:draft.instructionId,trade_id:draft.tradeId,instruction_digest:draft.idempotencyKey}});
export const cashfreeSplitRequest:SettlementRequestBuilder=draft=>({order_id:draft.instructionId,order_amount:draft.grossAmount,order_currency:draft.currency,splits:[{vendor_id:draft.supplierId,amount:draft.supplierEntitlement},{vendor_id:draft.sablestoneBeneficiaryId,amount:draft.sablestoneEntitlement}],order_note:`protected trade ${draft.tradeId}`});
export const razorpayRouteRequest:SettlementRequestBuilder=draft=>({transfers:[{account:draft.supplierId,amount:draft.supplierEntitlement,currency:draft.currency,on_hold:true,notes:{trade_id:draft.tradeId}},{account:draft.sablestoneBeneficiaryId,amount:draft.sablestoneEntitlement,currency:draft.currency,on_hold:true,notes:{trade_id:draft.tradeId,kind:"brokerage"}}]});
export const bankEscrowRequest:SettlementRequestBuilder=draft=>({instruction_id:draft.instructionId,gross_amount:draft.grossAmount,currency:draft.currency,beneficiaries:[{id:draft.supplierId,amount:draft.supplierEntitlement,role:"SELLER"},{id:draft.sablestoneBeneficiaryId,amount:draft.sablestoneEntitlement,role:"BROKER"}],release_conditions:draft.releaseConditions,dispute_procedure:draft.disputeProcedure,expires_at:draft.expiresAt});
export const lcProceedsRequest:SettlementRequestBuilder=draft=>({instruction_id:draft.instructionId,credit_beneficiary:draft.supplierId,assignee:draft.sablestoneBeneficiaryId,assigned_amount:draft.sablestoneEntitlement,currency:draft.currency,bank_acknowledgement_required:true,trade_id:draft.tradeId});
